apiVersion: v1
kind: Service
metadata:
  name: piwigo
  namespace: piwigo
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: piwigo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piwigo
  namespace: piwigo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piwigo
  template:
    metadata:
      labels:
        app: piwigo
    spec:
      containers:
        - name: piwigo
          image: lscr.io/linuxserver/piwigo:16.3.0-ls332
          ports:
            - containerPort: 80

          # 新增：把 Secret 里的 key/value 全部注入为环境变量
          envFrom:
            - secretRef:
                name: piwigo-db-secret

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Taipei"

          volumeMounts:
            - name: piwigo-data
              mountPath: /config
      volumes:
        - name: piwigo-data
          persistentVolumeClaim:
            claimName: piwigo-data
