apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: piwigo
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piwigo-data
  namespace: piwigo
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
