apiVersion: v1
kind: Secret
metadata:
  name: limesurvey-db-secret
  namespace: limesurvey
type: Opaque
stringData:
  DB_HOST: 10.32.65.22
  DB_PORT: "3306"
  DB_NAME: LimeSurvey
  DB_USER: limesurvey
  DB_PASSWORD: yJBfxRfp576jPRpf
  DB_CHARSET: utf8mb4
  DB_COLLATION: utf8mb4_unicode_ci
