apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikijs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/qzblue/ESP-K3S-Argoapps.git"
    targetRevision: main
    path: apps/wikijs
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wikijs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
