apiVersion: v1
kind: Secret
metadata:
  name: wikijs-db
  namespace: wikijs
type: Opaque
stringData:
  # MySQL 密码（来自用户）
  DB_PASS: "sJEY82wEeXKeic6w"
  # MySQL 用户（便于引用）
  DB_USER: "wikijs"
  # Wiki.js 初始管理员凭证（由用户提供）
  WIKI_ADMIN_EMAIL: "james.zhu@esp.edu.mo"
  WIKI_ADMIN_PASSWORD: "Qq389510848.."
