apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: limesurvey
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/qzblue/ESP-K3S-Argoapps.git
    targetRevision: main
    path: apps/limesurvey/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: limesurvey
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
